schema_version: 1

context:
  name: pyroomacoustics
  version: "0.10.1"
  build_number: 0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 26aa7d680e68d0b947220026b95b1c5a05eee08f38c53ff49a7804672c0a2886
  patches:
    - remove-build-deps-from-runtime-metadata.patch
    - use-system-cmake-dependencies.patch

build:
  number: ${{ build_number }}
  script:
    - if: unix
      then:
        - export CMAKE_GENERATOR=Ninja
        - python -m pip install . -vv --no-deps --no-build-isolation
    - if: win
      then:
        - python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - cmake
        - cython
        - nanoflann
        - ninja
        - numpy
        - pip
        - pybind11
        - python
        - setuptools
        - setuptools-scm
        - wheel
  host:
    - cmake
    - cython
    - eigen
    - nanoflann
    - ninja
    - numpy  # for global pinnings
    - numpy >=1.13.0
    - pip
    - pybind11
    - python
    - setuptools
    - setuptools-scm
    - wheel
  run:
    # numpy has run exports
    - python
    - scipy >=0.18.0

tests:
  - python:
      imports:
        - pyroomacoustics
  - script:
      - python run_test.py
      - pip check
    files:
      recipe:
        - run_test.py
    requirements:
      run:
        - pip
        - python

about:
  homepage: https://github.com/LCAV/pyroomacoustics
  repository: https://github.com/LCAV/pyroomacoustics
  summary: Pyroomacoustics is a package for audio signal processing for indoor applications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
